version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-208-103.compute-1.amazonaws.com
            database: d7omaeqpf58rpu
            schema: public
            user: parpipffvjmabf
            password: 56d5a5a038e4dd8dc4a748ad4cddd7dd2e4b6eb335e730b9f782923ff006ae25
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true